import { DrizzleService } from "@/services/drizzle-service.server";
import { createClipOperations } from "@/services/db-clip-operations.server";
import { createVideoOperations } from "@/services/db-video-operations.server";
import { createPlanOperations } from "@/services/db-plan-operations.server";
import { createRepoOperations } from "@/services/db-repo-operations.server";
import { createVersionOperations } from "@/services/db-version-operations.server";
import { createLessonSectionOperations } from "@/services/db-lesson-section-operations.server";
import { createLinkAuthOperations } from "@/services/db-link-auth-operations.server";
import { createThumbnailOperations } from "@/services/db-thumbnail-operations.server";
import { Effect } from "effect";

export class DBFunctionsService extends Effect.Service<DBFunctionsService>()(
  "DBFunctionsService",
  {
    effect: Effect.gen(function* () {
      const db = yield* DrizzleService;

      const {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
      } = createClipOperations(db);

      const {
        getRepoById,
        getRepoByFilePath,
        getRepoWithSectionsById,
        getRepoWithSectionsByFilePath,
        getRepos,
        getArchivedRepos,
        createRepo,
        updateRepoName,
        updateRepoMemory,
        updateRepoArchiveStatus,
        updateRepoFilePath,
        deleteRepo,
      } = createRepoOperations(db);

      const {
        getVideoDeepById,
        getStandaloneVideos,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        getVideoWithClipsById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        updateVideoArchiveStatus,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getVideosForFewShotExamples,
      } = createVideoOperations(db, { getRepoWithSectionsById });

      const {
        getPlans,
        syncPlan,
        deletePlan,
        renamePlan,
        getArchivedPlans,
        updatePlanArchiveStatus,
      } = createPlanOperations(db);

      const {
        getRepoVersions,
        getLatestRepoVersion,
        getRepoVersionById,
        getRepoWithSectionsByVersion,
        getVersionWithSections,
        createRepoVersion,
        updateRepoVersion,
        deleteRepoVersion,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
      } = createVersionOperations(db);

      const {
        getLessonById,
        getLessonsBySectionId,
        getLessonWithHierarchyById,
        getSectionWithHierarchyById,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        updateSectionOrder,
        updateSectionPath,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
      } = createLessonSectionOperations(db);

      const {
        getLinks,
        createLink,
        deleteLink,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
      } = createLinkAuthOperations(db);

      const {
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        selectThumbnailForUpload,
        deselectAllThumbnails,
        deleteThumbnail,
      } = createThumbnailOperations(db);

      return {
        getClipById,
        getClipsByIds,
        updateClip,
        archiveClip,
        reorderClip,
        createClipSection,
        createClipSectionAtInsertionPoint,
        createClipSectionAtPosition,
        getClipSectionById,
        updateClipSection,
        archiveClipSection,
        reorderClipSection,
        appendClips,
        getLessonById,
        getLessonWithHierarchyById,
        getLessonsBySectionId,
        getSectionWithHierarchyById,
        createVideo,
        createStandaloneVideo,
        hasOriginalFootagePathAlreadyBeenUsed,
        updateVideo,
        deleteVideo,
        updateVideoPath,
        updateVideoLesson,
        getRepoById,
        getRepoByFilePath,
        getRepoWithSectionsById,
        getRepoWithSectionsByFilePath,
        getRepos,
        getArchivedRepos,
        getVideoById: getVideoDeepById,
        getVideoWithClipsById: getVideoWithClipsById,
        getStandaloneVideos,
        getAllStandaloneVideos,
        getArchivedStandaloneVideos,
        createRepo,
        createSections,
        createLessons,
        createGhostLesson,
        updateLesson,
        deleteLesson,
        deleteSection,
        updateSectionOrder,
        updateSectionPath,
        getSectionsByIds,
        getSectionsByRepoVersionId,
        updateLessonOrder,
        getNextVideoId,
        getPreviousVideoId,
        getNextLessonWithoutVideo,
        getRepoVersions,
        getLatestRepoVersion,
        getRepoVersionById,
        getRepoWithSectionsByVersion,
        getVersionWithSections,
        createRepoVersion,
        updateRepoVersion,
        updateRepoName,
        updateRepoMemory,
        updateRepoArchiveStatus,
        updateVideoArchiveStatus,
        updateRepoFilePath,
        deleteRepo,
        deleteRepoVersion,
        copyVersionStructure,
        getVideoIdsForVersion,
        getAllVersionsWithStructure,
        getPlans,
        syncPlan,
        deletePlan,
        renamePlan,
        getArchivedPlans,
        updatePlanArchiveStatus,
        getLinks,
        createLink,
        deleteLink,
        getVideosForFewShotExamples,
        getYoutubeAuth,
        upsertYoutubeAuth,
        updateYoutubeAccessToken,
        deleteYoutubeAuth,
        getAiHeroAuth,
        upsertAiHeroAuth,
        deleteAiHeroAuth,
        getThumbnailsByVideoId,
        createThumbnail,
        getThumbnailById,
        updateThumbnail,
        selectThumbnailForUpload,
        deselectAllThumbnails,
        deleteThumbnail,
      };
    }),
  }
) {}
