#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# One-time setup for verify-cvm's test database (docs/plans/verify-test-database.md,
# Option A): a local Postgres 17 holding cvm_verify_template, a cvm_verify role
# that can clone it, ~/.config/cvm/verify.env pointing at it, and the first
# snapshot. Matt runs this himself: its last stage reads production.
#
#   pnpm setup:verify-db        (or ./scripts/setup-verify-db.sh)

if [[ -n "${CLAUDECODE:-}" || ! -t 0 ]]; then
  echo "setup-verify-db: run this from your own terminal — its last stage reads production." >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
ENV_FILE="$HOME/.config/cvm/verify.env"  # where write_env lands; holds one key
CONTAINER="cvm-local-postgres"           # the db:clone-local container
CONTAINER_PORT=5433
CONTAINER_SUPERUSER_PASSWORD="localpassword" # same as apps/local/scripts/clone-db-to-local.sh
ROLE="cvm_verify"
TEMPLATE_DB="cvm_verify_template"

PG_MODE=""   # docker | apt
PG_PORT=""

# superuser_sql "SQL" — run one statement as the server's superuser, print
# its result unaligned.
superuser_sql() {
  if [[ "$PG_MODE" == docker ]]; then
    docker exec -i "$CONTAINER" psql -X -v ON_ERROR_STOP=1 -q -At -U postgres -c "$1"
  else
    sudo -u postgres psql -X -v ON_ERROR_STOP=1 -q -At -p "$PG_PORT" -c "$1"
  fi
}

TOTAL_STAGES=6

banner "verify-cvm test database: one-time setup"

# ── 1 ───────────────────────────────────────────────────────────────────────
stage "Choose how Postgres 17 runs in WSL"
say "verify-cvm clones a local template database per run. It needs a Postgres 17"
say "server reachable from WSL. Two ways:"
printf '\n'
step "${BOLD}docker${RESET}: turn on Docker Desktop's WSL integration and reuse the"
note "        $CONTAINER container that 'pnpm db:clone-local' uses (port $CONTAINER_PORT)."
step "${BOLD}apt${RESET}:    install postgresql-17 from the PGDG apt repo (port 5432 usually)."
note "        Also brings pg_dump 17, so snapshots need no container."
printf '\n'
while [[ "$PG_MODE" != docker && "$PG_MODE" != apt ]]; do
  ask PG_MODE "Type docker or apt:"
done

# ── 2 ───────────────────────────────────────────────────────────────────────
if [[ "$PG_MODE" == docker ]]; then
  stage "Docker: WSL integration and the $CONTAINER container"
  if ! docker info >/dev/null 2>&1; then
    say "docker does not work inside WSL yet. In Docker Desktop on Windows:"
    step "Settings (gear icon) → Resources → WSL integration"
    step "Turn on the toggle for this distro (${WSL_DISTRO_NAME:-the one you run this from})"
    step "Click 'Apply & restart', then open a NEW WSL terminal if this one still fails"
    until docker info >/dev/null 2>&1; do
      pause "Press Enter once that's done (checking 'docker info')…"
      docker info >/dev/null 2>&1 || warn "docker still can't reach Docker Desktop — check the toggle and retry"
    done
  fi
  printf '  %s✓%s docker works in WSL\n' "$GREEN" "$RESET"

  if docker ps --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    printf '  %s✓%s %s is running\n' "$GREEN" "$RESET" "$CONTAINER"
  elif docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER"; then
    say "Starting the existing $CONTAINER container…"
    docker start "$CONTAINER" >/dev/null
  else
    say "No $CONTAINER container yet. This creates it (postgres:17, port $CONTAINER_PORT),"
    say "the same way 'pnpm db:clone-local' would."
    confirm "Create it now?" || { warn "can't continue without a server"; exit 1; }
    docker run -d --name "$CONTAINER" \
      -e POSTGRES_PASSWORD="$CONTAINER_SUPERUSER_PASSWORD" \
      -e POSTGRES_DB="ai-app-template" \
      -p "${CONTAINER_PORT}:5432" postgres:17 >/dev/null
  fi
  say "Waiting for Postgres to accept connections…"
  for _ in $(seq 1 30); do
    docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 && break
    sleep 1
  done
  docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 || { warn "$CONTAINER never became ready"; exit 1; }
  PG_PORT="$CONTAINER_PORT"
  printf '  %s✓%s Postgres 17 ready on localhost:%s\n' "$GREEN" "$RESET" "$PG_PORT"
  note "After a reboot: docker start $CONTAINER"
else
  stage "apt: install postgresql-17"
  if [[ -x /usr/lib/postgresql/17/bin/postgres ]]; then
    printf '  %s✓%s postgresql-17 is already installed\n' "$GREEN" "$RESET"
  else
    say "This adds the PostgreSQL project's apt repo (PGDG) and installs Postgres 17."
    say "It runs, with sudo:"
    note "  sudo apt install -y postgresql-common"
    note "  sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y"
    note "  sudo apt install -y postgresql-17"
    confirm "Run these now?" || { warn "can't continue without a server"; exit 1; }
    sudo apt install -y postgresql-common
    sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
    sudo apt install -y postgresql-17
  fi
  sudo service postgresql start >/dev/null 2>&1 || true
  PG_PORT="$(pg_lsclusters -h 2>/dev/null | awk '$1 == 17 { print $3; exit }')"
  [[ -n "$PG_PORT" ]] || { warn "no Postgres 17 cluster found (pg_lsclusters) — create one: sudo pg_createcluster 17 main --start"; exit 1; }
  printf '  %s✓%s Postgres 17 cluster on localhost:%s\n' "$GREEN" "$RESET" "$PG_PORT"
  note "After a WSL restart: sudo service postgresql start"
fi
pause

# ── 3 ───────────────────────────────────────────────────────────────────────
stage "Create the $ROLE role (LOGIN, CREATEDB)"
say "verify runs connect as $ROLE. CREATEDB lets them clone the template per run"
say "and drop the clone after. It is not a superuser and never sees production."
EXISTING_URL="$(_existing VERIFY_DATABASE_URL || true)"
if [[ -n "$EXISTING_URL" ]]; then
  # Re-run: keep the password already in verify.env, so live runs keep working.
  ROLE_PASSWORD="$(sed -E 's#^[a-z]*://[^:]*:([^@]*)@.*#\1#' <<< "$EXISTING_URL")"
  note "reusing the password already in $ENV_FILE"
else
  ROLE_PASSWORD="$(openssl rand -hex 16 2>/dev/null || head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  note "generated a random password — it only guards a local throwaway database"
fi
if [[ "$(superuser_sql "select 1 from pg_roles where rolname = '$ROLE'")" == 1 ]]; then
  superuser_sql "alter role $ROLE login createdb password '$ROLE_PASSWORD'"
  printf '  %s✓%s updated role %s\n' "$GREEN" "$RESET" "$ROLE"
else
  superuser_sql "create role $ROLE login createdb password '$ROLE_PASSWORD'"
  printf '  %s✓%s created role %s\n' "$GREEN" "$RESET" "$ROLE"
fi
pause

# ── 4 ───────────────────────────────────────────────────────────────────────
stage "Write $ENV_FILE"
say "verify.sh reads VERIFY_DATABASE_URL from here. The file holds that one key,"
say "outside the repo, so an agent never has to open .env to find a database."
mkdir -p "$(dirname "$ENV_FILE")"
VERIFY_DATABASE_URL="postgresql://$ROLE:$ROLE_PASSWORD@localhost:$PG_PORT/$TEMPLATE_DB"
write_env VERIFY_DATABASE_URL "$VERIFY_DATABASE_URL"
chmod 600 "$ENV_FILE"
if psql -X -q "postgresql://$ROLE:$ROLE_PASSWORD@localhost:$PG_PORT/postgres" -c 'select 1' >/dev/null 2>&1; then
  printf '  %s✓%s %s can log in on localhost:%s\n' "$GREEN" "$RESET" "$ROLE" "$PG_PORT"
else
  warn "$ROLE could not log in on localhost:$PG_PORT — check the server's pg_hba.conf allows password logins on 127.0.0.1"
  SKIPPED+=("make $ROLE able to log in on localhost:$PG_PORT")
fi
pause

# ── 5 ───────────────────────────────────────────────────────────────────────
stage "First snapshot: production → $TEMPLATE_DB"
say "This is the only step that touches production, and it only reads it:"
step "pg_dump production, skipping the data of youtube_auth, ai_hero_auth,"
note "  dropbox_auth and api_token (no OAuth tokens or API token hashes leave)"
step "restore it into $TEMPLATE_DB, check it, swap it in"
note "Rerun it whenever you want fresher data:  pnpm db:verify-snapshot"
note "It will ask you to type 'snapshot' to confirm."
if confirm "Run the snapshot now?"; then
  (cd "$REPO_ROOT" && ./scripts/verify-snapshot.sh) ||
    { warn "the snapshot failed — fix the error above, then: pnpm db:verify-snapshot"; SKIPPED+=("pnpm db:verify-snapshot"); }
else
  SKIPPED+=("pnpm db:verify-snapshot  (until then, verify runs fail with 'template does not exist')")
fi
pause

# ── 6 ───────────────────────────────────────────────────────────────────────
stage "Check verify-cvm sees it"
"$REPO_ROOT/.claude/skills/verify-cvm/scripts/verify.sh" mode >/dev/null 2>/tmp/verify-mode.$$ || true
sed 's/^/  /' /tmp/verify-mode.$$; rm -f /tmp/verify-mode.$$
say ""
say "Every verify-cvm launch from now on runs on its own clone of $TEMPLATE_DB."
note "To go back to production mode, delete $ENV_FILE."
pause

finish
